Feature/customer review
mxm-kotyk/team-project-icecream pull request #15
Opened 2022-12-24 18:30 UTC by Ernest-Kurish

Customer review section is done

2022-12-25 10:25 UTC, mxm-kotyk requested changes
Коли ти прописуєш медіаправило то не потрібно там повторювати код який ти прописав в звичайному стані (вище медіаправила), там прописують тільки те, що міняється.
Крапки пагінації стоять заблизько одна до одної. І передивися відступ між ними і swiper__title - він на різних версіях сайту різний.

2022-12-25 10:25 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +        background-attachment: fixed;
Ти це все прописав вище, не потрібного його прописувати кожен раз в медіаправилі. Всі аналогічні рядки нижче таж не потрібні.

2022-12-25 10:25 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +    width: 280px;
Це краще замінити на max-width - щоб елемент стискався, при зменшенні екрану (хоча не знаю чи хтось сидить з таких мобільних, але краще прописати)

2022-12-25 10:25 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +        width: 968px;
Тут завелика ширина прописана - катка не поміщається у в'юпорт

2022-12-25 10:25 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +    border-radius: 10px;
Бордер радіус змінюється на різних версіях сайту

2022-12-25 10:25 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +    padding: 35px 39px;
Падінги змінюються в залежності від версії сайту

2022-12-25 10:25 UTC, mxm-kotyk commented on src/partials/customer-reviews.html
> +        ./images/cust-diana-2x.jpg      2x
Аватарки скрізь однакові - не треба створювати окремо для таблета

2022-12-25 11:54 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        background-attachment: fixed;
Done.

2022-12-25 11:54 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +    width: 280px;
Done.

2022-12-25 11:55 UTC, Ernest-Kurish commented on src/partials/customer-reviews.html
> +        ./images/cust-diana-2x.jpg      2x
Done.

2022-12-25 11:56 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        width: 968px;
Changed to max-width: 100%;

2022-12-25 11:58 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +    border-radius: 10px;
Done.

2022-12-25 12:01 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +    padding: 35px 39px;
Done.

2022-12-25 12:01 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +    width: 280px;
Done.

2022-12-25 12:01 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        background-attachment: fixed;
Done.

2022-12-25 12:30 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +        width: 968px;
Та нє, не потрібно, щоб ширина розтягувалася весь час. Просто пропиши на кожен в'юпорт відповідну ширину по макету:
початковий - max 280 (ти це вже вище прописав)
таблет - 705
десктоп - 968

2022-12-25 12:42 UTC, mxm-kotyk requested changes
В тебе все ще є лишній код в медіаправилах до фонового зображення.
Пагінація в мобільній версії тепер відсунута вниз задалеко, там маютьбути такі відступи:
мобільний - 12
таблет і десктоп - 32 (в тебе 40 чомусь)

2022-12-25 12:42 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +        padding: 39px 109px 47px 109px;
Тут падінги мають бути  такі: верхній і нижній по 28, бокові по 80

2022-12-25 12:42 UTC, mxm-kotyk commented on src/sass/components/_customer_reviews.scss
> +        padding: 39px 109px 47px 109px;
Тут верхній і нижній падінги мають бути по 43

2022-12-25 15:22 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        width: 968px;
Done.

2022-12-25 15:25 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        padding: 39px 109px 47px 109px;
Done.

2022-12-25 15:26 UTC, Ernest-Kurish commented on src/sass/components/_customer_reviews.scss
> +        padding: 39px 109px 47px 109px;
Done

2022-12-26 15:10 UTC, mxm-kotyk reviewed
Ппропиши на селектор .swiper такі нижні падінги: до планшетної версії 12px, а для планшетної і десктопної 32px.

2022-12-26 15:10 UTC, mxm-kotyk commented on src/sass/components/_gallery.scss
> +    border-radius: 24px;
Радіус куточків на різних версіях сайту різна, звірся з макетом

2022-12-26 15:47 UTC, Ernest-Kurish commented
> Ппропиши на селектор .swiper такі нижні падінги: до планшетної версії 12px, а для планшетної і десктопної 32px.

Done.

2022-12-26 15:50 UTC, Ernest-Kurish commented on src/sass/components/_gallery.scss
> +    border-radius: 24px;
Done.
Mobile 8px
Tablet 18px
Desktop 24px

2022-12-26 17:20 UTC, merged